---
  ###
  ###
  # INSTALL KUBECTX
  ###
  ###
  - name: Download Kubectx
    ansible.builtin.get_url:
      url: "https://github.com/ahmetb/kubectx/releases/download/v{{ kubectx_version }}/kubectx_v{{ kubectx_version }}_linux_x86_64.tar.gz"
      dest: /tmp/kubectx.tar.gz
      mode: '0640'

  - name: Untar Kubectx
    ansible.builtin.unarchive:
      src: /tmp/kubectx.tar.gz
      dest: /tmp
      remote_src: true

  - name: Copy Kubectx to /usr/local/bin
    ansible.builtin.copy:
      src: /tmp/kubectx
      dest: /usr/local/bin/kubectx
      owner: root
      group: root
      mode: '0755'
      remote_src: true


  - name: Remove LICENSE file in /tmp
    ansible.builtin.file:
      path: /tmp/LICENSE
      state: absent

  - name: Remove Kubectx file in /tmp
    ansible.builtin.file:
      path: /tmp/kubectx
      state: absent

  - name: Remove Kubectx tar file in /tmp
    ansible.builtin.file:
      path: /tmp/kubectx.tar.gz
      state: absent


  - name: Get Kubectx version
    ansible.builtin.command: "kubectx --version"
    register: kubectx_version

  - name: Display Kubectx version
    ansible.builtin.debug: msg="{{ kubectx_version.stdout }}"