---
  ###
  ###
  # CONFIGURE FIREWALL: https://docs.k3s.io/installation/requirements#inbound-rules-for-k3s-nodes
  ###
  ###
  - name: Disable UFW
    community.general.ufw:
      state: enabled
    when: firewall_enabled | bool == false

  - block:
    - name: Install UFW
      ansible.builtin.apt:
        name:
        - ufw
        state: present
        autoclean: yes

    - name: Start and enable UFW service
      ansible.builtin.systemd:
        name: ufw
        state: started
        enabled: yes

    - name: Check if UFW original config file exists?
      ansible.builtin.stat:
        path: /etc/default/ufw.orig
      register: ufw_conf_exists

    - name: Make a backup of UFW config file if original config file not exists
      ansible.builtin.copy:
        remote_src: yes
        src: /etc/default/ufw
        dest: /etc/default/ufw.orig
        force: no
      when: ufw_conf_exists.stat.exists | bool == false

    - name: Disable IPv6
      ansible.builtin.replace:
        path: /etc/default/ufw
        regexp: "^IPV6.*"
        replace: "IPV6=no"
      when: ipv6_enabled | bool == false

    - name: Enable IPv6
      ansible.builtin.replace:
        path: /etc/default/ufw
        regexp: "^IPV6.*"
        replace: "IPV6=yes"
      when: ipv6_enabled | bool == true

    - name: Set logging
      community.general.ufw:
        logging: 'low'

    - name: Allow all outgoing connections
      community.general.ufw:
        direction: outgoing
        default: allow

    - name: Deny all incoming connections
      community.general.ufw:
        direction: incoming
        default: deny

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: ssh
        proto: tcp
        comment: ssh

    - name: Allow inbound port of 6443/tcp for master node
      community.general.ufw:
        rule: allow
        port: 6443
        proto: tcp
        comment: Kubernetes API Server
      when: "ansible_inv_group_for_master in group_names"

    - name: Allow inbound port of 10250/tcp for worker node(s)
      community.general.ufw:
        rule: allow
        port: 10250
        proto: tcp
        comment: Kubelet API
      when: "ansible_inv_group_for_workers in group_names"

    - name: Allow inbound port of 10256/tcp for worker node(s)
      community.general.ufw:
        rule: allow
        port: 10256
        proto: tcp
        comment: kube-proxy
      when: "ansible_inv_group_for_workers in group_names"

    - name: Allow inbound port of 443/tcp for worker node(s)
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp
        comment: https
      when: "ansible_inv_group_for_workers in group_names"

    - name: Allow inbound port of 80/tcp for worker node(s)
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp
        comment: http
      when: "ansible_inv_group_for_workers in group_names"

    - name: Allow inbound ports of 30000-32767/tcp for worker node(s)
      community.general.ufw:
        rule: allow
        port: 30000:32767
        proto: tcp
        comment: Kubernetes NodePort Services
      when: "ansible_inv_group_for_workers in group_names"

    - name: Allow inbound ports of 30000-32767/udp for worker node(s)
      community.general.ufw:
        rule: allow
        port: 30000:32767
        proto: udp
        comment: Kubernetes NodePort Services
      when: "ansible_inv_group_for_workers in group_names"

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    when: firewall_enabled | bool == true