---
  ###
  ###
  # INSTALL KUBENS
  ###
  ###
  - name: Download Kubens
    ansible.builtin.get_url:
      url: "https://github.com/ahmetb/kubectx/releases/download/v{{ kubens_version }}/kubens_v{{ kubens_version }}_linux_x86_64.tar.gz"
      dest: /tmp/kubens.tar.gz
      mode: '0640'

  - name: Untar Kubens
    ansible.builtin.unarchive:
      src: /tmp/kubens.tar.gz
      dest: /tmp
      remote_src: true

  - name: Copy Kubens to /usr/local/bin
    ansible.builtin.copy:
      src: /tmp/kubens
      dest: /usr/local/bin/kubens
      owner: root
      group: root
      mode: '0755'
      remote_src: true


  - name: Remove LICENSE file in /tmp
    ansible.builtin.file:
      path: /tmp/LICENSE
      state: absent

  - name: Remove kubens file in /tmp
    ansible.builtin.file:
      path: /tmp/kubens
      state: absent

  - name: Remove Kubens tar file in /tmp
    ansible.builtin.file:
      path: /tmp/kubens.tar.gz
      state: absent


  - name: Get Kubens version
    ansible.builtin.command: "kubens --version"
    register: kubens_version

  - name: Display Kubens version
    ansible.builtin.debug: msg="{{ kubens_version.stdout }}"