---
# task file for k3s-setup

- block:
  # 1. Disable Swap
  - ansible.builtin.include_tasks:
      file: 01_disable-swap-{{ ansible_distribution }}.yml
      apply:
        tags: "1"
    tags: "1"

  # 2. Configure IP Forwarding
  - ansible.builtin.include_tasks:
      file: 02_configure-ip-forwarding-{{ ansible_distribution }}.yml
      apply:
        tags: "2"
    tags: "2"

  # 3. Configure Firewall
  - ansible.builtin.include_tasks:
      file: 03_configure-firewall-{{ ansible_distribution }}.yml
      apply:
        tags: "3"
    tags: "3"

  # 4. Install K3s
  - ansible.builtin.include_tasks:
      file: 04_setup-k3s-master-{{ ansible_distribution }}.yml
      apply:
        tags: "4"
    when: "ansible_inv_group_for_master in group_names"
    tags: "4"

  # 5. Install Calico Network Plugin for Pod Networking
  - ansible.builtin.include_tasks:
      file: 05_calico-cni-{{ ansible_distribution }}.yml
      apply:
        tags: "5"
    tags: "5"

  # 6. Join Worker nodes to the Kubernetes Cluster
  - ansible.builtin.include_tasks:
      file: 06_join-k3s-cluster-{{ ansible_distribution }}.yml
      apply:
        tags: "6"
    tags: "6"

  # 7. Install Kubens
  - ansible.builtin.include_tasks:
      file: 07_install-kubens-{{ ansible_distribution }}.yml
      apply:
        tags: "7"
    when: kubens_enabled | bool == true
    tags: "7"

  when: ansible_distribution=="Ubuntu"