---
# task file for kubernetes-setup

# 1. Deploy NGINX Ingress Controller
- import_tasks: 01_deploy-ingress-nginx.yml
  when: nginx_controller_enabled | bool == true

# 2. Deploy MetalLB 
- import_tasks: 02_deploy-metallb.yml
  when: metallb_enabled | bool == true