---
# defaults file for kubernetes-setup

# Ansible Inventory group for Master node and Workers nodes
ansible_inv_group_for_master: k8s-master
ansible_inv_group_for_workers: k8s-worker

# Nodes' Firewall Configurations
ipv6_enabled: false
firewall_enabled: true

# Kubernetes Settings
# Latest Kubernetes version: https://github.com/kubernetes/kubernetes/releases
kubernetes_api_server_port: 6443
kubernetes_version: "1.29"   # Format: 1.YZ
kubernetes_pod_network_cidr: 172.16.0.0/16

# Calico Settings
# Latest Calico version: https://github.com/projectcalico/calico/releases
calico_version: 3.27.3  # Format: W.XY.Z

# Kubens Settings
# Latest Kubens version: https://github.com/ahmetb/kubectx/releases
kubens_enabled: true
kubens_version: 0.9.5  # Format: X.Y.Z